### ISSUE TITLE
Please update wiki

### ISSUE THREAD

**Issue by fake-or-dead** [omise/omise-ruby#1]
I found in wiki to set 
  Omise.api_key = "skey_test_4xa89ox4z4bcfrikkh2"

but after try out a little bit i found that should use "Omise.vault_key" instead 

;D

**Comment by robinclart** [comment]
`vault_key` is only needed when you have to query the Token API. And we do not recommend doing this on your web server because it means you're probably "poisoning" your environment with card holder data. Your skey should be set in `api_key` and pkey in `vault_key`. I'll update the readme later to explain this more clearly. Thanks :)

**Comment by fake-or-dead** [comment]
Hi @robinclart I just found out that version is update to 0.1.1 should i upgrade and any change log?

**Comment by robinclart** [comment]
Yeah you should. I fixed a few things and added the Refund API. Please test it first and if you encounter any regression please open an issue. I'll improve the README today and add a changelog. Thanks for the feedback.

**Comment by robinclart** [comment]
https://github.com/omise/omise-ruby/blob/master/CHANGELOG.md
